fix

diff --git a/etc/init/osx/install b/etc/init/osx/install
--- a/etc/init/osx/install
+++ b/etc/init/osx/install
@@ -25,10 +25,10 @@ fi
 
 # Rosetta2 でターミナルを動かしている時には強制終了させる
 if ! is_arm ; then
-	if is_rosseta2 ; then
-		echo "This script can not exec in Rosetta2 terminal. Abort."
-		exit 1
-	fi
+    if is_rosseta2 ; then
+        echo "This script can not exec in Rosetta2 terminal. Abort."
+        exit 1
+    fi
 fi
 
 # install homebrew
