fix for x86

diff --git a/etc/init/osx/install b/etc/init/osx/install
--- a/etc/init/osx/install
+++ b/etc/init/osx/install
@@ -20,9 +20,11 @@ is_rosseta2() {
 }
 
 # Rosetta2 でターミナルを動かしている時には強制終了させる
-if is_rosseta2 ; then
-	echo "This script can not exec in Rosetta2 terminal. Abort."
-	exit 1
+if ! is_arm ; then
+	if is_rosseta2 ; then
+		echo "This script can not exec in Rosetta2 terminal. Abort."
+		exit 1
+	fi
 fi
 
 # install homebrew
